### ISSUE TITLE
Rework Teams

### ISSUE THREAD

**Issue by Kamil-Majewski** [YourScheduler/YourScheduler.Web#5]
As a user i would like to be able to:
- create teams;
- assing administrators;
- invite people to team
- add a custom jpg file for team thumbnail;
- create posts in the team;
- create events in the team;
- use a shared team callendar;
- pass ownership;
- delete or edit team;
- have moderating options over team;

**Comment by kUcLis** [comment]
Created Entities and Repositories for TEAM and TEAMROLES
